spring.application.name=API-REST-Gestion-Tareas

# Configuracion del Puerto - Puerto por defecto es el 8080
server.port=8080

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate Config
# Sincronizacion de la entidad con la BD - Si se agrega un nuevo atributo/tabla, se creara en la BD
# Para desarrollo rapido se usa el update, pero para produccion se usa validate o none
spring.jpa.hibernate.ddl-auto=update
# Es fundamental porque le dice a Hibernate que imprima en la consola cada consulta SQL que traduce los metodos del repositorio (.save, .findAll(), findById())
spring.jpa.show-sql=true
# Da formato estetico al imprimir SQL en la consola, lo que nos ayuda a evitar de tener una sola linea de texto gigante
spring.jpa.properties.hibernate.format_sql=true
